#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
This script is used to perform automatic quality control (autoQC) on the data
generated by the tractometry flow pipeline. The QC is based on the Interquartile Range (IQR) 
method and a priori knowledge of the data. 

The a priori knowledge is based on the following metrics:
- streamline_count : < 10
- volume : < 100
- mean_length : < 20 or > 200

The script will generate a summary of the number of subjects excluded for each bundle and metric, 
and the original dataframe with the QC status.

Script returns:
- df_autoqc.csv : Dataframe with the QC status.
- autoqc_symmary.csv : Summary of the number of subjects excluded for each bundle and metric.
- box_volume_bundle.html : Boxplot of the volume for each bundle before QC.
- box_mean_length_bundle.html : Boxplot of the mean length for each bundle before QC.
- box_streamline_count_bundle.html : Boxplot of the streamline count for each bundle before QC.

"""

import argparse
import os

import pandas as pd
import numpy as np
import plotly.express as px

from scilpy.io.utils import (add_overwrite_arg,
                             assert_inputs_exist)



def _build_arg_parser():
    p = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter,
                                description=__doc__)

    p.add_argument('in_csv',
                   help='CSV File containing the csv average stats (.csv).')

    p.add_argument('--profile',
                   help='CSV File containing for the profile stats (.csv).')
    p.add_argument('--out_csv',
                   help='Output CSV filename for the stats (.csv).')
    p.add_argument('--out_dir',
                   help='Output directory to save CSV. \n'
                   'By default is current folder.')
    

    add_overwrite_arg(p)

    return p


def main():
    parser = _build_arg_parser()
    args = parser.parse_args()

    assert_inputs_exist(parser, args.in_csv)

    pd.options.mode.chained_assignment = None

    if args.out_dir is None:
        args.out_dir = './'

    # Load csv data
    df = pd.read_csv(args.in_csv)

    if args.profile:
        pf = pd.read_csv(args.profile)


    df[['QC_bundles','QC_IQR']] = "Pass"

    # Save the data
    if args.out_csv is not None:
        df_outliers.to_csv(os.path.join(args.out_dir, args.out_csv), index=False)
        if args.profile:
            args.out_csv = args.out_csv + '_profile.csv'
            pf.to_csv(os.path.join(args.out_dir, args.out_csv), index=False)
    else:
        outname = (os.path.splitext(os.path.basename(args.in_csv))[0]) + '_autoqc.csv'
        df_outliers.to_csv(os.path.join(args.out_dir,
                                        outname), index=False)
        if args.profile:
            outname = (os.path.splitext(os.path.basename(args.profile))[0]) + '_autoqc.csv'
            pf.to_csv(os.path.join(args.out_dir, outname), index=False)

    


if __name__ == '__main__':
    main()





