#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Metrics renaming
measure_dict = {"radODF" : 'Radial ODF', "fa" : 'FA', "md": 'MD', "rd" : 'RD', "ad": 'AD',
                "fw" : 'FW', "fat" : 'FA-FWcorrected', "mdt": 'MD-FWcorrected',
                "rdt" : 'RD-FWcorrected', "adt": 'AD-FWcorrected', "ecvf" : 'ECVF',
                "icvf": 'ICVF', "od" : 'OD', "isovf": 'ISOVF', "afd_total": 'AFD total',
                "afd_along" : 'AFD fixel', "nufo": 'NuFO', "volume" : 'Volume',
                "streamline_count": 'Count', "length" : 'Lenght',
                "MTR" : 'MTR', "ihMTR": 'ihMTR', "MTsat" : 'MTsat', "ihMTsat": 'ihMTdR1sat'}

list_metrics = [['NuFO','nufo','AFD total','afd_total','AFD fixel','afd_along',
                 'Radial ODF', 'radODF'],
                ['FA','AD','RD','MD','fa','ad','rd','md'],
                ['FA-FWcorrected', 'MD-FWcorrected','RD-FWcorrected',
                 'AD-FWcorrected','fat', 'mdt','rdt','adt'],
                ['FW', 'fw'],
                ['ECVF','ICVF','ISOVF','OD','ecvf','icvf','isovf','od'],
                ['MTR','MTsat','ihMTR','ihMTdR1sat','ihMTsat','mtr','mtsat',
                 'ihmtr','ihmtsat','ihmtdR1sat'],
                ['Volume','Count','volume','count','Length','min_length']]

list_method = ['HARDI',
               'DTI',
               'DTI-FW',
               'FW',
               'NODDI',
               'MTI',
               'Streamlines']

scaling_metrics = ['AD','RD','MD','ad','rd','md','mdt','rdt','adt',
                   'MD-FWcorrected','RD-FWcorrected','AD-FWcorrected']

#########
order_plot_dict = {'DTI':['FA','RD','MD','AD'],
                   'DTI-FW':['FA-FWcorrected', 'MD-FWcorrected', 'RD-FWcorrected',
                   'AD-FWcorrected'],
                   'FW':['FW'],
                   'HARDI':['AFD total','NuFO'],
                   'NODDI':['ICVF','OD','ECVF','ISOVf'],
                   'MTI':['ihMTR','MTR','ihMTdR1sat','MTsat'],
                   'Streamlines':['Volume','Count','Lenght']}

average_parameters_dict = {"FA" : [0,0.8], "MD": [0,0.16], "RD" : [0,0.16], "AD": [0,0.18],
                           "FW" : [0,1], "FA-FWcorrected" : [0,0.8], "MD-FWcorrected": [0,0.16],
                           "RD-FWcorrected" : [0,0.16], "AD-FWcorrected": [0,0.16],
                           "ECVF" : [0,1], "ICVF": [0,1], "OD" : [0,0.8], "ISOVF": [0,0.6],
                           "AFD total" : [0,1], "NuFO" : [0,3], "AFD fixel" : [0,1], "Radial ODF" :[0,1],
                           "Volume" : [],"Count": [], "Lenght" : [],
                           "MTR" : [0,30], "ihMTR": [0,18], "MTsat" : [0,6], "ihMTdR1sat": [0,0.4]}

# Reorder heatmap matrice 'ECVF',
new_order_measure = ['FA','AD','MD','RD','FA-FWcorrected',
                     'AD-FWcorrected', 'MD-FWcorrected',
                     'RD-FWcorrected','FW','AFD total','NuFO',
                     'ICVF','ISOVF','OD','MTR', 'MTsat', 'ihMTR',
                     'ihMTdR1sat']

# Metrics color list
metric_colors = {'AD': '#FEC840', 'FA': '#EE0000', 'MD': '#C57019','RD': '#FE9637',
                'ad': '#FEC840', 'fa': '#EE0000', 'md': '#C57019','rd': '#FE9637',
                'AFD total': '#33cc33','NuFO': '#877B04', 'AFD fixel':'#198032',
                'afd_total': '#33cc33','nufo': '#877B04', 'afd_along':'#198032',
                'Radial ODF': '#00CCAA', 'radODF': '#00CCAA',
                'ECVF': '#4CBDD5', 'ICVF': '#1395A9', 'ISOVF': '#4CBDD5','OD': '#00AEA1',
                'ecvf': '#4CBDD5', 'icvf': '#1395A9', 'isovf': '#4CBDD5','od': '#00AEA1',
                'MTR': '#8000FF', 'MTsat': '#A291F3','mtr': '#8000FF', 'mtsat': '#A291F3',
                'ihMTR': '#C03EEA', 'ihMTdR1sat': '#FC66AB','ihmtr': '#C03EEA',
                'ihmtdR1sat': '#FC66AB', 'ihMTsat': '#FC66AB', 'ihmtsat': '#FC66AB',
                'FW': '#178DFF','fw': '#178DFF',
                'AD-FWcorrected': '#E9EC38', 'FA-FWcorrected': '#FC6666',
                'MD-FWcorrected': '#E6891E', 'RD-FWcorrected': '#FEBE17',
                'adt': '#E9EC38', 'fat': '#FC6666','mdt': '#E6891E', 'rdt': '#FEBE17',
                'Volume':'#333333','Count':'#770302'}


# Bundles color list
bundle_dict_color_v1 = {"AF": "#368a6b", "AF Left": "#368a6b","AF Right": "#368a6b",
                        "CC 7": "#047b3c", "CC 6": "#00ffea", "CC 5": "#0544c4",
                        "CC 4":"#fa7e08", "CC 3": "#82830e", "CC 2b": "#bcbb73",
                        "CC 2a": "#fe8ad5", "CC 1":"#ff4707",
                        "CC_7": "#047b3c", "CC_6": "#00ffea", "CC_5": "#0544c4",
                        "CC_4":"#fa7e08", "CC_3": "#82830e", "CC_2b": "#bcbb73",
                        "CC_2a": "#fe8ad5", "CC_1":"#ff4707",
                        "CG": "#ffff00", "CG Left": "#ffff00","CG Right": "#ffff00",
                        "CG_L": "#ffff00","CG_R": "#ffff00",
                        "CST": "#1b0385","CST Left": "#1b0385", "CST Right": "#1b0385",
                        "CST_L": "#1b0385", "CST_R": "#1b0385",
                        "IFOF": "#f9c306", "IFOF Left": "#f9c306", "IFOF Right": "#f9c306",
                        "IFOF_L": "#f9c306", "IFOF_R": "#f9c306",
                        "ILF": "#11d473","ILF Left": "#11d473", "ILF Right": "#11d473",
                        "ILF_L": "#11d473", "ILF_R": "#11d473",
                        "SLF 1": "#d9cef5","SLF 1 Left": "#d9cef5", "SLF 1 Right": "#d9cef5",
                        "SLF_1": "#d9cef5", "SLF_1_L": "#d9cef5", "SLF_1_R": "#d9cef5",
                        "SLF 2": "#9a82d7", "SLF 2 Left": "#9a82d7", "SLF 2 Right": "#9a82d7",
                        "SLF_2": "#9a82d7", "SLF_2_L": "#9a82d7", "SLF_2_R": "#9a82d7",
                        "SLF 3": "#615481","SLF 3 Left": "#615481", "SLF 3 Right": "#615481",
                        "SLF_3": "#615481","SLF_3_L": "#615481", "SLF_3_R": "#615481",
                        "OR": "#7ab5af", "OR Left": "#7ab5af", "OR Right": "#7ab5af",
                        "OR_L": "#7ab5af", "OR_R": "#7ab5af",
                        "UF": "#7541f8", "UF Left": "#7541f8", "UF Right": "#7541f8",
                        "UF_L": "#7541f8", "UF_R": "#7541f8",
                        "CR_L": "#a9a9a9", "CR_R": "#a9a9a9", "CR": "#a9a9a9",
                        "CR Left": "#a9a9a9", "CR Right": "#a9a9a9",
                        "MCP":"#C34095",
                        "ICP":"#400080", "ICP Left":"#400080", "ICP Right":"#400080",
                        "ICP_L":"#400080", "ICP_R":"#400080"}

bundle_dict_color_v10 = {"AC":"#D31558",
                   "AF": "#368a6b", "AF Left": "#368a6b","AF Right": "#368a6b",
                   "AF_L": "#368a6b","AF_R": "#368a6b",
                   "CC Temporal": "#91F7C0", "CC_Te": "#91F7C0",
                   "CC PrePost":"#B5706F","CC_Pr_Po":"#B5706F",
                   "CC Parietal": "#F75D6A", "CC_Pa": "#F75D6A",
                   "CC Occipital": "#7F8F22", "CC_Oc": "#7F8F22",
                   "CC Frontal Superior": "#C1BB62","CC_Fr_1": "#C1BB62",
                   "CC Frontal Inferior":"#E7BEF0","CC_Fr_2":"#E7BEF0",
                   "CG": "#FFFF00", "CG Left": "#FFFF00","CG Right": "#FFFF00",
                   "CG_L": "#FFFF00","CG_R": "#FFFF00",
                   "CG Anterior": "#FFED7F","CG_An": "#FFED7F",
                   "CG Anterior Left": "#FFED7F","CG_L_An": "#FFED7F",
                   "CG Anterior Right": "#FFED7F","CG_R_An": "#FFED7F",
                   "CG Curve": "#FFEC00",  "CG_curve": "#FFEC00",
                   "CG Curve Left": "#FFEC00","CG_L_curve": "#FFEC00",
                   "CG Curve Right": "#FFEC00","CG_R_curve": "#FFEC00",
                   "CG Posterior": "#F69A00", "CG_Po": "#F69A00",
                   "CG Posterior Left": "#F69A00", "CG_L_Po": "#F69A00",
                   "CG Posterior Right": "#F69A00", "CG_R_Po": "#F69A00",
                   "FAT": "#A5CCBF","FAT Left": "#A5CCBF", "FAT Right": "#A5CCBF",
                   "FAT_L": "#A5CCBF", "FAT_R": "#A5CCBF",
                   "FTP": "#247DB6","FTP Left": "#247DB6", "FTP Right": "#247DB6",
                   "FTP_L": "#247DB6", "FTP_R": "#247DB6",
                   "Fornix": "#191919","fornix group": "#191919",
                   "Fornix Left": "#191919", "Fornix Right": "#191919",
                   "FX": "#191919","FX_L": "#191919", "FX_R": "#191919",
                   "ICP":"#400080", "ICP Left":"#400080", "ICP Right":"#400080",
                   "ICP_L":"#400080", "ICP_R":"#400080",
                   "IFOF": "#7F6FC1", "IFOF Left": "#7F6FC1", "IFOF_L": "#7F6FC1",
                   "IFOF Right": "#7F6FC1", "IFOF_R": "#7F6FC1",
                   "ILF": "#11D473","ILF Left": "#11D473", "ILF_L": "#11D473",
                   "ILF Right": "#11D473", "ILF_R": "#11D473",
                   "MCP":"#C34095",
                   "MdLF": "#D9CEF5", "MdLF Left": "#D9CEF5", "MdLF_L": "#D9CEF5",
                   "MdLF Right": "#D9CEF5", "MdLF_R": "#D9CEF5",
                   "OR": "#95D0CC", "OR Left": "#95D0CC", "OR_L": "#95D0CC",
                   "OR Right": "#95D0CC", "OR_R": "#95D0CC",
                   "PC": "#ED000A",
                   "POPT": "#2A38F3", "POPT Left": "#2A38F3", "POPT_L": "#2A38F3",
                   "POPT Right": "#2A38F3", "POPT_R": "#2A38F3",
                   "PYT": "#1B0385", "PYT Left": "#1B0385", "PYT_L": "#1B0385",
                   "PYT Right": "#1B0385", "PYT_R": "#1B0385",
                   "SCP":"#C6F1EA", "SCP Left":"#C6F1EA", "SCP_L":"#C6F1EA",
                   "SCP Right":"#C6F1EA", "SCP_R":"#C6F1EA",
                   "SLF": "#9A82D7", "SLF Left": "#9A82D7", "SLF_L": "#9A82D7",
                   "SLF Right": "#9A82D7", "SLF_R": "#9A82D7",
                   "UF": "#7541F8", "UF Left": "#7541F8", "UF_L": "#7541F8",
                   "UF Right": "#7541F8", "UF_R": "#7541F8"
                   }
